// Datos de ejemplo para el catálogo de juegos
const juegos = [
    {
        id: 1,
        nombre: "7 Days to Die",
        consola: "playstation",
        genero: ["aventura", "accion"],
        year: 2013,
        imagen: "https://www.theactionpixel.com/wp-content/uploads/2016/04/7daystodie_title.jpg",
        descripcion: "Explora el reino de Hyrule en esta épica aventura de mundo abierto. Enfréntate a peligros, resuelve rompecabezas y derrota al malvado Ganon para salvar al reino.",
        desarrollador: "The Fun Pimps",
        puntuacion: 97,
        precio: 59.99,
        multijugador: false
    },
    {
        id: 2,
        nombre: "A Plague Tale Innocence",
        consola: "playstation",
        genero: ["accion", "aventura"],
        year: 2022,
        imagen: "https://c4.wallpaperflare.com/wallpaper/581/28/1024/video-games-playstation-4-a-plague-tale-innocence-hd-wallpaper-preview.jpg",
        descripcion: "La historia sigue a Amicia y a su hermano pequeño Hugo, quienes intentan sobrevivir en un mundo cruel y brutal asolado por la guerra y la Peste Negra.",
        desarrollador: "Asobo Studio",
        puntuacion: 81,
        multijugador: false
    },
    {
        id: 3,
        nombre: "Halo Infinite",
        consola: "xbox",
        genero: ["accion", "shooter"],
        year: 2021,
        imagen: "https://images.unsplash.com/photo-1605979399824-ea3aceaefaed?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "El Jefe Maestro regresa en esta nueva entrega de la legendaria saga Halo. Lucha contra un nuevo enemigo en un mundo abierto lleno de posibilidades.",
        desarrollador: "343 Industries",
        puntuacion: 87,
        precio: 59.99,
        multijugador: true
    },
    {
        id: 4,
        nombre: "Cyberpunk 2077",
        consola: "pc",
        genero: ["rpg", "accion"],
        year: 2020,
        imagen: "https://images.unsplash.com/photo-1614294149010-950b698f72c0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Sumérgete en Night City, una megalópolis obsesionada con el poder, el glamour y las modificaciones corporales en este RPG de mundo abierto.",
        desarrollador: "CD Projekt Red",
        puntuacion: 86,
        precio: 49.99,
        multijugador: false
    },
    {
        id: 5,
        nombre: "Spider-Man: Miles Morales",
        consola: "playstation",
        genero: ["accion", "aventura"],
        year: 2020,
        imagen: "https://images.unsplash.com/photo-1560343776-97e7d202ff0e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Miles Morales descubre poderes explosivos que lo diferencian de su mentor, Peter Parker. Domina sus habilidades únicas para convertirte en un nuevo Spider-Man.",
        desarrollador: "Insomniac Games",
        puntuacion: 85,
        precio: 49.99,
        multijugador: false
    },
    {
        id: 6,
        nombre: "Animal Crossing: New Horizons",
        consola: "nintendo",
        genero: ["simulacion", "estrategia"],
        year: 2020,
        imagen: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Escapa a una isla desierta y crea tu paraíso personal mientras recolectas recursos, construyes herramientas y haces amigos con encantadores animales.",
        desarrollador: "Nintendo",
        puntuacion: 90,
        precio: 59.99,
        multijugador: true
    },
    {
        id: 7,
        nombre: "Forza Horizon 5",
        consola: "xbox",
        genero: ["carreras", "deportes"],
        year: 2021,
        imagen: "https://images.unsplash.com/photo-1585407611057-3e181965687c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Explora los paisajes dinámicos y en constante evolución de México en cientos de los mejores autos del mundo en esta experiencia de carreras definitiva.",
        desarrollador: "Playground Games",
        puntuacion: 92,
        precio: 59.99,
        multijugador: true
    },
    {
        id: 8,
        nombre: "Elden Ring",
        consola: "pc",
        genero: ["rpg", "accion"],
        year: 2022,
        imagen: "https://images.unsplash.com/photo-1536506545709-a7b99b733dae?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Un RPG de acción épico ambientado en un mundo creado por Hidetaka Miyazaki y George R. R. Martin. Explora las Tierras Intermedias y desafía a enemigos legendarios.",
        desarrollador: "FromSoftware",
        puntuacion: 96,
        precio: 59.99,
        multijugador: true
    },
    {
        id: 9,
        nombre: "Final Fantasy VII Remake",
        consola: "playstation",
        genero: ["rpg", "accion"],
        year: 2020,
        imagen: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Una reimaginación del clásico RPG que sigue a Cloud Strife, un ex-SOLDADO que se une a una organización eco-terrorista para luchar contra la corporación Shinra.",
        desarrollador: "Square Enix",
        puntuacion: 87,
        precio: 59.99,
        multijugador: false
    },
    {
        id: 10,
        nombre: "Super Mario Odyssey",
        consola: "nintendo",
        genero: ["plataformas", "aventura"],
        year: 2017,
        imagen: "https://images.unsplash.com/photo-1531594652722-322307b2a22e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Acompaña a Mario en una aventura épica en 3D por todo el mundo, usando sus nuevas habilidades para recoger lunas y desbloquear nuevos y emocionantes lugares.",
        desarrollador: "Nintendo",
        puntuacion: 97,
        precio: 59.99,
        multijugador: false
    },
    {
        id: 11,
        nombre: "Horizon Forbidden West",
        consola: "playstation",
        genero: ["accion", "rpg", "aventura"],
        year: 2022,
        imagen: "https://images.unsplash.com/photo-1518182170546-07661fd94144?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "Aloy se aventura en el Oeste Prohibido, una frontera majestuosa pero peligrosa que oculta nuevas y misteriosas amenazas.",
        desarrollador: "Guerrilla Games",
        puntuacion: 88,
        precio: 69.99,
        multijugador: false
    },
    {
        id: 12,
        nombre: "Red Dead Redemption 2",
        consola: "xbox",
        genero: ["accion", "aventura"],
        year: 2018,
        imagen: "https://images.unsplash.com/photo-1516900448138-fc1826cab4dd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        descripcion: "América, 1899. El fin de la era del Salvaje Oeste ha comenzado. Sigue la historia de Arthur Morgan y la banda de Van der Linde mientras luchan por sobrevivir.",
        desarrollador: "Rockstar Games",
        puntuacion: 97,
        precio: 39.99,
        multijugador: true
    }
]; 